kind: ConfigMap 
apiVersion: v1 
metadata:
  name: frontdoor-config
  namespace: echo 
data:
  config.yaml: |
    httpbin.echo: httpbin.echo:80
    echo-http.echo: echo.echo:8080
    echo-https.echo: echo.echo:8443