apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontdoor
  namespace: echo
  labels:
    app: frontdoor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontdoor
  template:
    metadata:
      labels:
        app: frontdoor
    spec:
      containers:
      - name: frontdoor
        image: docker.io/pszeto/frontdoor
        imagePullPolicy: Always
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
        - name: CONfIG_DIR
          value: "/etc/config/frontdoor"
        - name: REWRITE_X_FORWARD_PROTO
          value: "true"
        - name: ADD_X_REQUEST_ID
          value: "true"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
          - mountPath: /etc/config/frontdoor
            name: frontdoor-config
      volumes:
      - name: frontdoor-config
        configMap:
          name: frontdoor-config
