kind: Service
apiVersion: v1
metadata:
  name: frontdoor
  namespace: echo
spec:
  selector:
    app: frontdoor
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443